name: Build and Upload Windows VHD

on:
  push:
    branches:
      - main
      - user/vhd_pipeline_automation

jobs:
  build-upload-vhd:
    name: Build and Upload VHD
    runs-on:
      - self-hosted
      - windows
      - hyperv

    env:
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      AZURE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display runner info
        shell: pwsh
        run: |
          Write-Output "Runner OS: $env:RUNNER_OS"
          Write-Output "PowerShell version: $($PSVersionTable.PSVersion)"

      - name: Ensure Hyper-V is enabled (Elevated)
        shell: pwsh
        run: |
          Start-Process pwsh -ArgumentList "-Command `"& {
            `$hv = Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All
            if (`$hv.State -ne 'Enabled') {
              throw 'Hyper-V is not enabled.'
            }
            Write-Output 'Hyper-V is enabled.'
          }`"" -Verb RunAs -Wait

      - name: Install Chocolatey, Packer, and Azure CLI (Elevated)
        shell: pwsh
        run: |
          Start-Process pwsh -ArgumentList "-Command `"& {
            if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
              Set-ExecutionPolicy Bypass -Scope Process -Force
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
              Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
            }

            if (-not (Get-Command packer -ErrorAction SilentlyContinue)) {
              choco install packer -y
            }

            if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
              choco install azure-cli -y
            }
          }`"" -Verb RunAs -Wait

      - name: Initialize and Validate Packer
        shell: pwsh
        run: |
          packer plugins install github.com/hashicorp/hyperv
          packer init windows.json.pkr.hcl
          packer fmt -var-file='windows.auto.pkrvars.hcl' 'windows.json.pkr.hcl'
          packer validate -var-file='windows.auto.pkrvars.hcl' 'windows.json.pkr.hcl'

      - name: Build VHD using Packer
        shell: pwsh
        run: |
          packer build -force -var-file='windows.auto.pkrvars.hcl' 'windows.json.pkr.hcl'

      - name: Locate generated VHD
        shell: pwsh
        run: |
          $vhdFile = Get-ChildItem -Path './output' -Filter '*.vhd*' -Recurse | Select-Object -First 1
          if ($null -eq $vhdFile) {
            throw "No VHD file found."
          }
          Write-Output "VHD_PATH=$($vhdFile.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Output "Found VHD: $($vhdFile.FullName)"

      - name: Upload VHD to Azure Blob Storage
        shell: pwsh
        run: |
          az storage blob upload `
            --account-name $env:AZURE_STORAGE_ACCOUNT `
            --account-key $env:AZURE_STORAGE_KEY `
            --container-name $env:AZURE_CONTAINER_NAME `
            --file "$env:VHD_PATH" `
            --name (Split-Path -Path "$env:VHD_PATH" -Leaf) `
            --overwrite
          Write-Output "Uploaded VHD: $(Split-Path -Path "$env:VHD_PATH" -Leaf)"